cccam: Fix build
ERROR: enigma2-plugin-softcams-cccam-2.3.2-r0 do_package_qa: QA Issue: /usr/bin/CCcam contained in package enigma2-plugin-softcams-cccam
requires libcrypt.so.1, but no providers found in RDEPENDS_enigma2-plugin-softcams-cccam? [file-rdeps]
ERROR: enigma2-plugin-softcams-cccam-2.3.2-r0 do_package_qa: QA Issue: /usr/bin/CCcam contained in package enigma2-plugin-softcams-cccam
requires libcrypt.so.1(GLIBC_2.4), but no providers found in RDEPENDS_enigma2-plugin-softcams-cccam? [file-rdeps]
ERROR: enigma2-plugin-softcams-cccam-2.3.2-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.