nfs-utils: Don't remove bash
ERROR: nfs-utils-2.3.3-r0 do_package_qa: QA Issue: /sbin/osd_login contained in package nfs-utils
requires /bin/bash, but no providers found in RDEPENDS_nfs-utils? [file-rdeps]