openvison-version-info: Append INSANE_SKIP file-rdeps
ERROR: openvision-version-info-9.1-r1 do_package_qa: QA Issue: /etc/init.d/openvision-timesync.sh contained in package openvision-version-info
requires /usr/bin/sh, but no providers found in RDEPENDS_openvision-version-info? [file-rdeps]