openvision-version-info: Don't build with dreamone
openvision-development-platform/build/tmp/work/dreamone-oe-linux/openvision-module/1.0-r0/openvisionmodule.c:53:17:
error: unused variable 'begin' [-Werror=unused-variable]
|    53 |         off_t   begin = 0;

/openvision-development-platform/build/tmp/work-shared/dreamone/kernel-source/include/linux/module.h:139:7: error:
'cleanup_module' specifies less restrictive attribute than its target 'cleanup_openvisionmodule': 'cold' [-Werror=missing-attributes]
|   139 |  void cleanup_module(void) __attribute__((alias(#exitfn)));

/openvision-development-platform/build/tmp/work/dreamone-oe-linux/openvision-module/1.0-r0/openvisionmodule.c:17:31:
 error: 'Our_Proc_Dir' defined but not used [-Werror=unused-variable]
|    17 | static struct proc_dir_entry* Our_Proc_Dir;
|       |                               ^~~~~~~~~~~~