enigma2-alliance-plugins: Remove astra-sm from DEPENDS
ERROR: openvision-enigma2-image-1.0-r0 do_rootfs: Postinstall scriptlets of ['astra-sm'] have failed.
If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

---

astra-sm still added to RDEPENDS.
It does buid and is included in image.