gstreamer: Update to git HEAD
Apply patch to fix build.

../../../git/sys/nvcodec/gstnvbaseenc.c:980:12: error: unused variable 'cuda_ret' [-Werror=unused-variable]
|   980 |   CUresult cuda_ret;